version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:? postgres user is needed}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:? postgres password is needed}
      - POSTGRES_DB=${POSTGRES_DB:? postgres db name is needed}

  server:
    image: node:latest
    working_dir: /node/app
    volumes:
      - ./server:/node/app
    env_file:
      - ./.env
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mongo-db: 