version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    command: --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:? mongo user is needed}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:? mongo password is needed}
      - MONGO_INITDB_DATABASE=${MONGO_DB:? mongo db name is needed}
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:? postgres user is needed}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:? postgres password is needed}
      - POSTGRES_DB=${POSTGRES_DB:? postgres db name is needed}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
