version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo:/data/db
      - ./docker/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:? postgres user is needed}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:? postgres password is needed}
      - POSTGRES_DB=${POSTGRES_DB:? postgres db name is needed}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
