name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        backend-path: [server]
        frontend-path: [client]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Node.js 20.x
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install backend dependencies
        working-directory: ${{ matrix.backend-path }}
        run: pnpm install

      - name: Install frontend dependencies
        working-directory: ${{ matrix.frontend-path }}
        run: pnpm install

      - name: Build front-end
        working-directory: ${{ matrix.frontend-path }}
        run: pnpm run build

      - name: Remove existing backend files
        run: sudo rm -rf /var/www/html/server/*

      - name: Remove existing frontend files
        run: sudo rm -rf /var/www/html/client/*

      - name: Remove previous backend files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/html/server/*

      - name: Deploy backend to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ${{ matrix.backend-path }}
          target: '/var/www/html/server'
          overwrite: true

      - name: Set backend permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/html/server/
            sudo chmod -R 755 /var/www/html/server/
            sudo find /var/www/html/server/ -type d -exec chmod 755 {} \;
            sudo find /var/www/html/server/ -type f -exec chmod 644 {} \;

      - name: Remove previous frontend files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/html/client/*

      - name: Restart back-end
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          workdir: /var/www/html/server
          script: |
            /home/ubuntu/.local/share/pnpm/pm2 restart server.js

      - name: Deploy frontend to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ${{ matrix.frontend-path }}/dist
          target: '/var/www/html/client'

      - name: Set frontend permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/html/client/
            sudo chmod -R 755 /var/www/html/client/
            sudo find /var/www/html/client/ -type d -exec chmod 755 {} \;
            sudo find /var/www/html/client/ -type f -exec chmod 644 {} \;
