on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            directory: [server, client]
    steps:
      - name: Checkout
        uses: actions/checkout@v3






