name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        backend-path: [server]
        frontend-path: [client]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Node.js 20.x
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install backend dependencies
        working-directory: ${{ matrix.backend-path }}
        run: pnpm install

      - name: Install frontend dependencies
        working-directory: ${{ matrix.frontend-path }}
        run: pnpm install

      - name: Build front-end
        working-directory: ${{ matrix.frontend-path }}
        run: pnpm run build

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ${{ matrix.backend-path }}
          target: '/var/www/html'
          script: |
              chown -R www-data:www-data /var/www/html/server/
              chmod -R 755 /var/www/html/server/

      - name: Restart back-end
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          workdir: /var/www/html/server
          script: |
            pm2 restart server.js

      - name: Deploy front-end
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ${{ matrix.frontend-path }}/dist
          target: '/var/www/html/client'
